/**
 * Seed venue data for Family Fun in Bmore
 *
 * 10 real-ish Baltimore venues near Patterson Park (within 5 miles)
 * Used for demo purposes — coordinates are approximate
 */

export interface VenueData {
  title: string
  slug: string
  venueType: string
  description: string
  address: string
  neighborhood: string
  latitude: number
  longitude: number
  distanceFromPark: number
  capacity: number
  hourlyRate: number
  hasKitchen: boolean
  hasGymnasium: boolean
  alcoholPolicy: string
  adaAccessible: boolean
  parkingSpaces: number
  imageUrl: string
  heroImageUrl: string
  contactPhone: string
  contactEmail: string
  amenities: string
  rating: number
  reviewCount: number
}

export const VENUES: VenueData[] = [
  {
    title: "St. Elizabeth of Hungary Church Hall",
    slug: "st-elizabeth-church-hall",
    venueType: "church",
    description: "A beautifully maintained parish hall in the heart of Highlandtown, just steps from Patterson Park. The hall features high ceilings, a fully equipped commercial kitchen, and seating for up to 150 guests. Perfect for family celebrations, community dinners, and milestone events. The space retains its classic charm with original woodwork and stained glass accents.",
    address: "234 S Ellwood Ave, Baltimore, MD 21224",
    neighborhood: "Highlandtown",
    latitude: 39.2890,
    longitude: -76.5693,
    distanceFromPark: 0.3,
    capacity: 150,
    hourlyRate: 75,
    hasKitchen: true,
    hasGymnasium: false,
    alcoholPolicy: "none",
    adaAccessible: true,
    parkingSpaces: 30,
    imageUrl: "https://images.unsplash.com/photo-1510070112810-d4e9a46d9e91?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1510070112810-d4e9a46d9e91?w=1200&h=600&fit=crop",
    contactPhone: "(410) 276-1041",
    contactEmail: "hall@stelizabethbmore.org",
    amenities: "tables,chairs,kitchen,sound_system,parking",
    rating: 4.7,
    reviewCount: 23,
  },
  {
    title: "Sacred Heart of Jesus Parish Center",
    slug: "sacred-heart-parish-center",
    venueType: "church",
    description: "A spacious parish center with a warm, welcoming atmosphere perfect for large family gatherings. The recently renovated space accommodates up to 200 guests with a modern commercial kitchen and flexible floor plan. Located in Highlandtown with easy access from Eastern Ave.",
    address: "600 S Conkling St, Baltimore, MD 21224",
    neighborhood: "Highlandtown",
    latitude: 39.2862,
    longitude: -76.5652,
    distanceFromPark: 0.5,
    capacity: 200,
    hourlyRate: 85,
    hasKitchen: true,
    hasGymnasium: false,
    alcoholPolicy: "none",
    adaAccessible: true,
    parkingSpaces: 45,
    imageUrl: "https://images.unsplash.com/photo-1438032005730-c779502df39b?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1438032005730-c779502df39b?w=1200&h=600&fit=crop",
    contactPhone: "(410) 342-4545",
    contactEmail: "center@sacredheartbmore.org",
    amenities: "tables,chairs,kitchen,sound_system,parking,stage",
    rating: 4.5,
    reviewCount: 31,
  },
  {
    title: "Patterson Park Recreation Center",
    slug: "patterson-park-rec-center",
    venueType: "rec_center",
    description: "The crown jewel of Baltimore's recreation centers, located right on the edge of Patterson Park. Features a full-size gymnasium, multipurpose room, and kitchen facilities. Ideal for youth events, sports parties, and active family gatherings. The gym can be configured for basketball, volleyball, or open play.",
    address: "27 S Ellwood Ave, Baltimore, MD 21224",
    neighborhood: "Patterson Park",
    latitude: 39.2916,
    longitude: -76.5697,
    distanceFromPark: 0.1,
    capacity: 100,
    hourlyRate: 50,
    hasKitchen: true,
    hasGymnasium: true,
    alcoholPolicy: "none",
    adaAccessible: true,
    parkingSpaces: 20,
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=600&fit=crop",
    contactPhone: "(410) 396-9235",
    contactEmail: "pprec@baltimorecity.gov",
    amenities: "tables,chairs,kitchen,gymnasium,wifi,parking",
    rating: 4.3,
    reviewCount: 47,
  },
  {
    title: "Southeast Anchor Library Community Room",
    slug: "southeast-anchor-library",
    venueType: "library",
    description: "A modern, bright community room inside Baltimore's newest library branch. The space seats up to 50 guests with floor-to-ceiling windows overlooking Eastern Avenue. Built-in projector and screen, high-speed WiFi, and a quiet, professional atmosphere. Perfect for smaller gatherings, showers, and meetings.",
    address: "3601 Eastern Ave, Baltimore, MD 21224",
    neighborhood: "Highlandtown",
    latitude: 39.2882,
    longitude: -76.5567,
    distanceFromPark: 0.8,
    capacity: 50,
    hourlyRate: 40,
    hasKitchen: false,
    hasGymnasium: false,
    alcoholPolicy: "none",
    adaAccessible: true,
    parkingSpaces: 15,
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=600&fit=crop",
    contactPhone: "(410) 396-1580",
    contactEmail: "seanchor@prattlibrary.org",
    amenities: "tables,chairs,projector,wifi",
    rating: 4.8,
    reviewCount: 18,
  },
  {
    title: "Creative Alliance at The Patterson",
    slug: "creative-alliance-patterson",
    venueType: "community_center",
    description: "A vibrant arts and community center housed in a beautifully restored historic theater. The main hall features exposed brick, artistic lighting, and a stage area. Full commercial kitchen and bar service available. One of Baltimore's most unique event spaces — perfect for creative celebrations and community gatherings.",
    address: "3134 Eastern Ave, Baltimore, MD 21224",
    neighborhood: "Highlandtown",
    latitude: 39.2887,
    longitude: -76.5610,
    distanceFromPark: 0.6,
    capacity: 175,
    hourlyRate: 125,
    hasKitchen: true,
    hasGymnasium: false,
    alcoholPolicy: "full_bar",
    adaAccessible: true,
    parkingSpaces: 25,
    imageUrl: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1200&h=600&fit=crop",
    contactPhone: "(410) 276-1651",
    contactEmail: "events@creativealliance.org",
    amenities: "tables,chairs,kitchen,sound_system,stage,projector,wifi,parking",
    rating: 4.9,
    reviewCount: 56,
  },
  {
    title: "Highlandtown Elementary Community Room",
    slug: "highlandtown-elementary",
    venueType: "school",
    description: "A versatile community space within Highlandtown Elementary, available evenings and weekends. Features a full gymnasium with basketball hoops, a cafeteria-style kitchen, and a separate meeting room. Great for kids' birthday parties, sports events, and youth group activities.",
    address: "3223 Eastern Ave, Baltimore, MD 21224",
    neighborhood: "Highlandtown",
    latitude: 39.2884,
    longitude: -76.5585,
    distanceFromPark: 0.7,
    capacity: 80,
    hourlyRate: 45,
    hasKitchen: true,
    hasGymnasium: true,
    alcoholPolicy: "none",
    adaAccessible: true,
    parkingSpaces: 20,
    imageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=1200&h=600&fit=crop",
    contactPhone: "(410) 396-9146",
    contactEmail: "community@highlandtownelem.org",
    amenities: "tables,chairs,kitchen,gymnasium,parking",
    rating: 4.2,
    reviewCount: 15,
  },
  {
    title: "Canton Waterfront Community Center",
    slug: "canton-waterfront-community",
    venueType: "community_center",
    description: "A modern community center with stunning waterfront views of Canton's harbor. The main event room features floor-to-ceiling windows, an outdoor patio, and a full kitchen. Licensed for beer and wine service. Walking distance to Canton's shops and restaurants — an upscale option for family celebrations.",
    address: "3301 Boston St, Baltimore, MD 21224",
    neighborhood: "Canton",
    latitude: 39.2792,
    longitude: -76.5722,
    distanceFromPark: 1.2,
    capacity: 120,
    hourlyRate: 110,
    hasKitchen: true,
    hasGymnasium: false,
    alcoholPolicy: "beer_wine",
    adaAccessible: true,
    parkingSpaces: 50,
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=600&fit=crop",
    contactPhone: "(410) 276-9560",
    contactEmail: "events@cantonwaterfront.org",
    amenities: "tables,chairs,kitchen,sound_system,projector,wifi,parking,patio",
    rating: 4.6,
    reviewCount: 38,
  },
  {
    title: "Hatton Senior Center Hall",
    slug: "hatton-senior-center",
    venueType: "community_center",
    description: "A cozy, well-maintained hall in the Hatton Senior Center, perfect for intimate family gatherings. The space has a warm, homey feel with a kitchen equipped for catering support. Known for its friendly staff and affordable rates. Ideal for baby showers, small birthday parties, and family dinners.",
    address: "2825 Fait Ave, Baltimore, MD 21224",
    neighborhood: "Canton",
    latitude: 39.2847,
    longitude: -76.5736,
    distanceFromPark: 0.4,
    capacity: 75,
    hourlyRate: 35,
    hasKitchen: true,
    hasGymnasium: false,
    alcoholPolicy: "none",
    adaAccessible: true,
    parkingSpaces: 15,
    imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1200&h=600&fit=crop",
    contactPhone: "(410) 396-9108",
    contactEmail: "hatton@baltimorecity.gov",
    amenities: "tables,chairs,kitchen,parking",
    rating: 4.4,
    reviewCount: 12,
  },
  {
    title: "St. Casimir Church Hall",
    slug: "st-casimir-church-hall",
    venueType: "church",
    description: "One of the largest church halls in Southeast Baltimore, the St. Casimir hall can accommodate up to 250 guests for banquet-style seating. The grand space features a raised stage, professional-grade sound system, and a massive commercial kitchen. Licensed for beer and wine service for special occasions.",
    address: "2800 O'Donnell St, Baltimore, MD 21224",
    neighborhood: "Canton",
    latitude: 39.2833,
    longitude: -76.5750,
    distanceFromPark: 0.9,
    capacity: 250,
    hourlyRate: 95,
    hasKitchen: true,
    hasGymnasium: false,
    alcoholPolicy: "beer_wine",
    adaAccessible: true,
    parkingSpaces: 60,
    imageUrl: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1200&h=600&fit=crop",
    contactPhone: "(410) 276-1214",
    contactEmail: "hall@stcasimirbmore.org",
    amenities: "tables,chairs,kitchen,sound_system,stage,parking",
    rating: 4.5,
    reviewCount: 42,
  },
  {
    title: "Fells Point Community Center",
    slug: "fells-point-community-center",
    venueType: "community_center",
    description: "A charming community center in historic Fells Point, steps from the waterfront. The exposed-brick interior and original hardwood floors give this space a warm, inviting character. Full bar service available. Popular for wedding receptions, milestone birthdays, and corporate events with a touch of Baltimore charm.",
    address: "1636 Thames St, Baltimore, MD 21231",
    neighborhood: "Fells Point",
    latitude: 39.2822,
    longitude: -76.5908,
    distanceFromPark: 1.8,
    capacity: 90,
    hourlyRate: 100,
    hasKitchen: true,
    hasGymnasium: false,
    alcoholPolicy: "full_bar",
    adaAccessible: false,
    parkingSpaces: 10,
    imageUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&h=400&fit=crop",
    heroImageUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1200&h=600&fit=crop",
    contactPhone: "(410) 563-2200",
    contactEmail: "events@fellspointcc.org",
    amenities: "tables,chairs,kitchen,sound_system,wifi",
    rating: 4.7,
    reviewCount: 29,
  },
]

export const EVENT_TYPES = [
  { value: "birthday_party", label: "Birthday Party", icon: "🎂" },
  { value: "family_reunion", label: "Family Reunion", icon: "👨‍👩‍👧‍👦" },
  { value: "baby_shower", label: "Baby Shower", icon: "👶" },
  { value: "wedding_reception", label: "Wedding Reception", icon: "💒" },
  { value: "community_meeting", label: "Community Meeting", icon: "🤝" },
  { value: "youth_group", label: "Youth Group Event", icon: "⚽" },
  { value: "religious_gathering", label: "Religious Gathering", icon: "🕊️" },
  { value: "corporate_event", label: "Corporate Event", icon: "💼" },
  { value: "other", label: "Other", icon: "✨" },
]

export const VENUE_TYPE_LABELS: Record<string, string> = {
  church: "Church Hall",
  rec_center: "Recreation Center",
  community_center: "Community Center",
  library: "Library",
  school: "School",
}

export const ALCOHOL_LABELS: Record<string, string> = {
  none: "No Alcohol",
  beer_wine: "Beer & Wine",
  full_bar: "Full Bar",
}
